# Generated by Django 5.1.1 on 2024-09-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('web', '0005_alter_member_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeterm',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='gradeattachment',
            name='badge_term',
        ),
        migrations.AddField(
            model_name='member',
            name='badges',
            field=models.ManyToManyField(related_name='members_with_badges', to='badges.badge'),
        ),
        migrations.AddField(
            model_name='member',
            name='wanted_badges',
            field=models.ManyToManyField(related_name='members_wanting_badges', to='badges.badge'),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='BadgeTerm',
        ),
        migrations.DeleteModel(
            name='GradeAttachment',
        ),
    ]
