# Generated by Django 5.1.1 on 2024-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('web', '0006_remove_badgeterm_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='members_with_badges', to='badges.badge'),
        ),
        migrations.AlterField(
            model_name='member',
            name='wanted_badges',
            field=models.ManyToManyField(blank=True, related_name='members_wanting_badges', to='badges.badge'),
        ),
    ]
