# Generated by Django 5.1.1 on 2024-10-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_remove_badgeterm_term_name_badgeterm_term_and_more'),
        ('web', '0007_alter_member_badges_alter_member_wanted_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='grading_of_wanted_badges_badges',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_with_grading', to='badges.gradeattachment'),
        ),
    ]
