# Generated by Django 5.1.1 on 2024-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_remove_badgeterm_term_name_badgeterm_term_and_more'),
        ('web', '0008_member_grading_of_wanted_badges_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='grading_of_wanted_badges_badges',
        ),
        migrations.AddField(
            model_name='member',
            name='grading_of_wanted_badges_badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='members_with_grading', to='badges.gradeattachment'),
        ),
    ]
