# Generated by Django 5.1.1 on 2024-10-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_member_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, upload_to='gallery_videos'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.district'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
