# Generated by Django 5.1.1 on 2024-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_gallery_video_alter_gallery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
