# Generated by Django 5.1.1 on 2024-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_event_display_on_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='video',
        ),
        migrations.AddField(
            model_name='gallery',
            name='file',
            field=models.FileField(blank=True, upload_to='gallery_files/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
