# Generated by Django 5.1.1 on 2024-10-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_gallery_image_remove_gallery_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='file',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='file_type',
        ),
        migrations.CreateModel(
            name='GalleryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='gallery_files/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.gallery')),
            ],
        ),
    ]
