# Generated by Django 5.1.1 on 2024-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_announcement_date_alter_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='district',
        ),
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.ManyToManyField(blank=True, null=True, to='web.district'),
        ),
    ]
