# Generated by Django 5.1.1 on 2024-10-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_member_district_member_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='district',
        ),
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='web.district'),
        ),
    ]
