# Generated by Django 5.1.1 on 2024-09-30 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='badge_images')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('grade', models.TextField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='badges.badge')),
            ],
        ),
        migrations.CreateModel(
            name='GradeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='grade_attachments/')),
                ('description', models.TextField(blank=True)),
                ('badge_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='badges.badgeterm')),
            ],
        ),
    ]
