# Generated by Django 5.1.1 on 2024-10-01 06:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
