# Generated by Django 5.1.1 on 2024-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_badge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
