# Generated by Django 5.1.1 on 2024-10-01 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='slug',
            field=models.SlugField(blank=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain letters, numbers, underscores, and hyphens.', regex='^[\\w-]+$')]),
        ),
    ]
