# Generated by Django 5.1.1 on 2024-10-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_alter_badge_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='slug',
        ),
    ]
