# Generated by Django 5.1.1 on 2024-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_remove_badgeterm_term_name_badgeterm_term_and_more'),
        ('web', '0010_remove_member_badges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeGradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('badge', models.ManyToManyField(related_name='grading_system', to='badges.badge')),
                ('badge_term', models.ManyToManyField(related_name='grading_system', to='badges.badgeterm')),
                ('member', models.ManyToManyField(related_name='grading_system', to='web.member')),
            ],
        ),
    ]
