# Generated by Django 5.1.1 on 2024-10-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0007_badgegradingsystem'),
        ('web', '0010_remove_member_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgegradingsystem',
            name='grade_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_system', to='badges.gradeattachment'),
        ),
        migrations.RemoveField(
            model_name='badgegradingsystem',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='badgegradingsystem',
            name='badge_term',
        ),
        migrations.RemoveField(
            model_name='badgegradingsystem',
            name='member',
        ),
        migrations.AddField(
            model_name='badgegradingsystem',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_system', to='badges.badge'),
        ),
        migrations.AddField(
            model_name='badgegradingsystem',
            name='badge_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_system', to='badges.badgeterm'),
        ),
        migrations.AddField(
            model_name='badgegradingsystem',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_system', to='web.member'),
        ),
    ]
