# Generated by Django 5.1.1 on 2024-10-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_alter_badgegradingsystem_grade_attachment'),
        ('web', '0017_remove_member_district_member_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('display_on_his_account', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_approval', to='badges.badge')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_approval', to='web.member')),
            ],
        ),
    ]
